In [1]:
import pandas as pd

In [2]:
new_df=pd.read_csv('../DataGathering/pdf_links_with_years.csv')

In [3]:
new_df.head()

   Year Week                                               Link
0  2024  1st  https://drive.google.com/file/d/1SsmjJf-wrTtau...
1  2024  2nd  https://drive.google.com/file/d/1LJdSIdb0D3WTd...
2  2024  3rd  https://drive.google.com/file/d/1BUQRAAr6jqLY1...
3  2024  4th  https://drive.google.com/file/d/1MRED1hxz6K8Ky...
4  2024  5th  https://drive.google.com/file/d/1ugVynaeUhTSP9...

In [4]:
df_2024 = new_df[new_df["Year"] == 2024]

In [5]:
df_2024.to_csv('./pdf_links_2024.csv', index=False)

In [6]:
df_2024.head()

   Year Week                                               Link
0  2024  1st  https://drive.google.com/file/d/1SsmjJf-wrTtau...
1  2024  2nd  https://drive.google.com/file/d/1LJdSIdb0D3WTd...
2  2024  3rd  https://drive.google.com/file/d/1BUQRAAr6jqLY1...
3  2024  4th  https://drive.google.com/file/d/1MRED1hxz6K8Ky...
4  2024  5th  https://drive.google.com/file/d/1ugVynaeUhTSP9...

# Pdf Downloading

In [7]:
# !pip install gdown

In [8]:
import os
import pandas as pd

download_folder = "downloads_2024"
os.makedirs(download_folder, exist_ok=True)

def get_file_id(url):
    """Extract Google Drive file ID from URL."""
    if "id=" in url:
        return url.split("id=")[-1]
    elif "/d/" in url:
        return url.split("/d/")[1].split("/")[0]
    return None

def download_drive_file(file_id, filename):
    """Download Google Drive file using wget."""
    file_path = os.path.join(download_folder, filename)
    download_url = f"https://drive.google.com/uc?export=download&id={file_id}"
    
    command = f"wget --no-check-certificate '{download_url}' -O '{file_path}'"
    os.system(command)
    print(f"✅ Downloaded: {file_path}")

# Download all files
for index, row in df_2024.iterrows():
    file_id = get_file_id(row["Link"])
    if file_id:
        filename = f"Week_{row['Week']}_2024.pdf"
        download_drive_file(file_id, filename)
    else:
        print(f"⚠️ Invalid Google Drive link: {row['Link']}")

print(f"📁 All files are saved in: {download_folder}")

--2025-03-03 19:32:23--  https://drive.google.com/uc?export=download&id=1SsmjJf-wrTtau9DM5YK3qthByCrmK7JE
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1SsmjJf-wrTtau9DM5YK3qthByCrmK7JE&export=download [following]
--2025-03-03 19:32:24--  https://drive.usercontent.google.com/download?id=1SsmjJf-wrTtau9DM5YK3qthByCrmK7JE&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 961723 (939K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_1st_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  350K 3s
    50K .......... .......... .......... .......... .......... 10%  567K 2s
   100K .......... .......... .......... .......... .......... 15%  872K 2s
   150K .......... .......... .......... .......... .......... 21% 2.89M 1s
   200K .......... .......... .......... .......... .......... 26% 2.00M 1s
   250K .......... .......... .......... .......... .......... 31% 1.62M 1s
   300K .......... .......... .......... .......... .......... 37% 2.77M 1s
   350K .......... .......... .......... .......... .......... 42% 6.86M 1s
   400K .......... .......... .......... .......... .......... 47% 3.51M 0s
   450K .......... .......... .......... .......... .......... 53% 5.95M 0s
   500K .......... .......... .......... .......... .......... 58% 2.35M 0s
   550K .......... .......... .......... .......... .......... 63% 4.04M 0s
   600K .......... .......... .......... .......... .......... 69% 5.81M 0s
   650K .......... .......... .......... .......... .......... 74% 8.90M 0s
   700K .......... .......... .......... .......... .......... 79% 5.49M 0s
   750K .......... .......... .......... .......... .......... 85% 9.35M 0s
   800K .......... .......... .......... .......... .......... 90% 7.03M 0s
   850K .......... .......... .......... .......... .......... 95% 3.17M 0s
   900K .......... .......... .......... .........            100% 11.8M=0.5s

2025-03-03 19:32:28 (1.86 MB/s) - ‘downloads_2024/Week_1st_2024.pdf’ saved [961723/961723]

--2025-03-03 19:32:28--  https://drive.google.com/uc?export=download&id=1LJdSIdb0D3WTdVSw_HkwVKJKaFU1gIA-
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_1st_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1LJdSIdb0D3WTdVSw_HkwVKJKaFU1gIA-&export=download [following]
--2025-03-03 19:32:29--  https://drive.usercontent.google.com/download?id=1LJdSIdb0D3WTdVSw_HkwVKJKaFU1gIA-&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 627311 (613K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_2nd_2024.pdf’

     0K .......... .......... .......... .......... ..........  8%  380K 1s
    50K .......... .......... .......... .......... .......... 16%  619K 1s
   100K .......... .......... .......... .......... .......... 24% 1.06M 1s
   150K .......... .......... .......... .......... .......... 32% 2.08M 1s
   200K .......... .......... .......... .......... .......... 40% 1.44M 0s
   250K .......... .......... .......... .......... .......... 48% 2.00M 0s
   300K .......... .......... .......... .......... .......... 57% 3.66M 0s
   350K .......... .......... .......... .......... .......... 65% 3.40M 0s
   400K .......... .......... .......... .......... .......... 73% 4.89M 0s
   450K .......... .......... .......... .......... .......... 81% 3.73M 0s
   500K .......... .......... .......... .......... .......... 89% 2.32M 0s
   550K .......... .......... .......... .......... .......... 97% 5.47M 0s
   600K .......... ..                                         100% 4.93M=0.4s

2025-03-03 19:32:33 (1.41 MB/s) - ‘downloads_2024/Week_2nd_2024.pdf’ saved [627311/627311]

--2025-03-03 19:32:33--  https://drive.google.com/uc?export=download&id=1BUQRAAr6jqLY1U6po6FwpfCEAErCCoEu
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_2nd_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1BUQRAAr6jqLY1U6po6FwpfCEAErCCoEu&export=download [following]
--2025-03-03 19:32:34--  https://drive.usercontent.google.com/download?id=1BUQRAAr6jqLY1U6po6FwpfCEAErCCoEu&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 660226 (645K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_3rd_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  348K 2s
    50K .......... .......... .......... .......... .......... 15%  622K 1s
   100K .......... .......... .......... .......... .......... 23% 1.35M 1s
   150K .......... .......... .......... .......... .......... 31% 1.20M 1s
   200K .......... .......... .......... .......... .......... 38% 2.66M 1s
   250K .......... .......... .......... .......... .......... 46% 3.25M 0s
   300K .......... .......... .......... .......... .......... 54% 2.43M 0s
   350K .......... .......... .......... .......... .......... 62% 2.16M 0s
   400K .......... .......... .......... .......... .......... 69% 2.84M 0s
   450K .......... .......... .......... .......... .......... 77% 11.5M 0s
   500K .......... .......... .......... .......... .......... 85% 3.90M 0s
   550K .......... .......... .......... .......... .......... 93% 8.27M 0s
   600K .......... .......... .......... .......... ....      100% 4.68M=0.4s

2025-03-03 19:32:38 (1.48 MB/s) - ‘downloads_2024/Week_3rd_2024.pdf’ saved [660226/660226]

--2025-03-03 19:32:38--  https://drive.google.com/uc?export=download&id=1MRED1hxz6K8KykUhFmOBZ_5Fz2HMgPfM
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_3rd_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1MRED1hxz6K8KykUhFmOBZ_5Fz2HMgPfM&export=download [following]
--2025-03-03 19:32:39--  https://drive.usercontent.google.com/download?id=1MRED1hxz6K8KykUhFmOBZ_5Fz2HMgPfM&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 740809 (723K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_4th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  248K 3s
    50K .......... .......... .......... .......... .......... 13%  434K 2s
   100K .......... .......... .......... .......... .......... 20%  928K 1s
   150K .......... .......... .......... .......... .......... 27% 1.01M 1s
   200K .......... .......... .......... .......... .......... 34% 1.23M 1s
   250K .......... .......... .......... .......... .......... 41%  899K 1s
   300K .......... .......... .......... .......... .......... 48% 4.93M 1s
   350K .......... .......... .......... .......... .......... 55% 3.06M 0s
   400K .......... .......... .......... .......... .......... 62% 1.82M 0s
   450K .......... .......... .......... .......... .......... 69% 2.90M 0s
   500K .......... .......... .......... .......... .......... 76% 1.56M 0s
   550K .......... .......... .......... .......... .......... 82% 3.44M 0s
   600K .......... .......... .......... .......... .......... 89% 2.58M 0s
   650K .......... .......... .......... .......... .......... 96% 5.53M 0s
   700K .......... .......... ...                             100% 2.36M=0.7s

2025-03-03 19:32:43 (1.06 MB/s) - ‘downloads_2024/Week_4th_2024.pdf’ saved [740809/740809]

--2025-03-03 19:32:43--  https://drive.google.com/uc?export=download&id=1ugVynaeUhTSP9wSPJEpnyFvm-yDwJYWD
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_4th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1ugVynaeUhTSP9wSPJEpnyFvm-yDwJYWD&export=download [following]
--2025-03-03 19:32:44--  https://drive.usercontent.google.com/download?id=1ugVynaeUhTSP9wSPJEpnyFvm-yDwJYWD&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 740512 (723K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_5th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  296K 2s
    50K .......... .......... .......... .......... .......... 13%  559K 2s
   100K .......... .......... .......... .......... .......... 20%  955K 1s
   150K .......... .......... .......... .......... .......... 27% 1.45M 1s
   200K .......... .......... .......... .......... .......... 34% 1.43M 1s
   250K .......... .......... .......... .......... .......... 41% 1.79M 1s
   300K .......... .......... .......... .......... .......... 48% 1.53M 0s
   350K .......... .......... .......... .......... .......... 55% 2.44M 0s
   400K .......... .......... .......... .......... .......... 62% 4.54M 0s
   450K .......... .......... .......... .......... .......... 69% 6.08M 0s
   500K .......... .......... .......... .......... .......... 76% 4.82M 0s
   550K .......... .......... .......... .......... .......... 82% 4.17M 0s
   600K .......... .......... .......... .......... .......... 89% 1.20M 0s
   650K .......... .......... .......... .......... .......... 96% 6.80M 0s
   700K .......... .......... ...                             100% 4.58M=0.6s

2025-03-03 19:32:50 (1.28 MB/s) - ‘downloads_2024/Week_5th_2024.pdf’ saved [740512/740512]

--2025-03-03 19:32:50--  https://drive.google.com/uc?export=download&id=171CIVyUf_g8WWV5iy-BBsxOJ-w3TjxeK
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_5th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=171CIVyUf_g8WWV5iy-BBsxOJ-w3TjxeK&export=download [following]
--2025-03-03 19:32:50--  https://drive.usercontent.google.com/download?id=171CIVyUf_g8WWV5iy-BBsxOJ-w3TjxeK&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 690248 (674K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_6th_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  358K 2s
    50K .......... .......... .......... .......... .......... 14%  601K 1s
   100K .......... .......... .......... .......... .......... 22% 1.41M 1s
   150K .......... .......... .......... .......... .......... 29% 1.13M 1s
   200K .......... .......... .......... .......... .......... 37% 2.12M 1s
   250K .......... .......... .......... .......... .......... 44% 2.36M 0s
   300K .......... .......... .......... .......... .......... 51% 1.25M 0s
   350K .......... .......... .......... .......... .......... 59% 4.64M 0s
   400K .......... .......... .......... .......... .......... 66% 5.17M 0s
   450K .......... .......... .......... .......... .......... 74% 4.68M 0s
   500K .......... .......... .......... .......... .......... 81% 5.55M 0s
   550K .......... .......... .......... .......... .......... 89% 4.97M 0s
   600K .......... .......... .......... .......... .......... 96% 8.79M 0s
   650K .......... .......... ....                            100% 5.60M=0.4s

2025-03-03 19:32:54 (1.49 MB/s) - ‘downloads_2024/Week_6th_2024.pdf’ saved [690248/690248]

--2025-03-03 19:32:54--  https://drive.google.com/uc?export=download&id=1p084F_Nkx3PvKFTnIUxUwfeT62epyzkX
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_6th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1p084F_Nkx3PvKFTnIUxUwfeT62epyzkX&export=download [following]
--2025-03-03 19:32:55--  https://drive.usercontent.google.com/download?id=1p084F_Nkx3PvKFTnIUxUwfeT62epyzkX&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 832525 (813K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_7th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  401K 2s
    50K .......... .......... .......... .......... .......... 12%  624K 1s
   100K .......... .......... .......... .......... .......... 18% 1.51M 1s
   150K .......... .......... .......... .......... .......... 24% 1.39M 1s
   200K .......... .......... .......... .......... .......... 30% 1.89M 1s
   250K .......... .......... .......... .......... .......... 36% 3.06M 1s
   300K .......... .......... .......... .......... .......... 43% 2.01M 0s
   350K .......... .......... .......... .......... .......... 49% 3.81M 0s
   400K .......... .......... .......... .......... .......... 55% 4.53M 0s
   450K .......... .......... .......... .......... .......... 61% 4.44M 0s
   500K .......... .......... .......... .......... .......... 67% 4.59M 0s
   550K .......... .......... .......... .......... .......... 73% 9.28M 0s
   600K .......... .......... .......... .......... .......... 79% 3.46M 0s
   650K .......... .......... .......... .......... .......... 86% 6.19M 0s
   700K .......... .......... .......... .......... .......... 92% 5.82M 0s
   750K .......... .......... .......... .......... .......... 98% 8.55M 0s
   800K .......... ...                                        100% 8.32M=0.4s

2025-03-03 19:33:00 (1.86 MB/s) - ‘downloads_2024/Week_7th_2024.pdf’ saved [832525/832525]

--2025-03-03 19:33:00--  https://drive.google.com/uc?export=download&id=1RPKEGDrNDELaz3LKfCCY9NC8kC8PufB4
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_7th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1RPKEGDrNDELaz3LKfCCY9NC8kC8PufB4&export=download [following]
--2025-03-03 19:33:00--  https://drive.usercontent.google.com/download?id=1RPKEGDrNDELaz3LKfCCY9NC8kC8PufB4&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 736802 (720K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_8th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  334K 2s
    50K .......... .......... .......... .......... .......... 13%  477K 2s
   100K .......... .......... .......... .......... .......... 20%  915K 1s
   150K .......... .......... .......... .......... .......... 27% 1.27M 1s
   200K .......... .......... .......... .......... .......... 34% 2.17M 1s
   250K .......... .......... .......... .......... .......... 41% 1.80M 1s
   300K .......... .......... .......... .......... .......... 48% 1.49M 0s
   350K .......... .......... .......... .......... .......... 55% 3.09M 0s
   400K .......... .......... .......... .......... .......... 62% 3.13M 0s
   450K .......... .......... .......... .......... .......... 69% 3.94M 0s
   500K .......... .......... .......... .......... .......... 76% 6.73M 0s
   550K .......... .......... .......... .......... .......... 83% 2.99M 0s
   600K .......... .......... .......... .......... .......... 90% 2.59M 0s
   650K .......... .......... .......... .......... .......... 97% 6.18M 0s
   700K .......... .........                                  100% 5.26M=0.5s

2025-03-03 19:33:05 (1.33 MB/s) - ‘downloads_2024/Week_8th_2024.pdf’ saved [736802/736802]

--2025-03-03 19:33:05--  https://drive.google.com/uc?export=download&id=1oOCt8avv_yfOlsQ047XjCwtEOM5dq5CC
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_8th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1oOCt8avv_yfOlsQ047XjCwtEOM5dq5CC&export=download [following]
--2025-03-03 19:33:06--  https://drive.usercontent.google.com/download?id=1oOCt8avv_yfOlsQ047XjCwtEOM5dq5CC&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 790156 (772K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_9th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  352K 2s
    50K .......... .......... .......... .......... .......... 12%  540K 2s
   100K .......... .......... .......... .......... .......... 19% 1.14M 1s
   150K .......... .......... .......... .......... .......... 25% 1.44M 1s
   200K .......... .......... .......... .......... .......... 32% 1.91M 1s
   250K .......... .......... .......... .......... .......... 38% 3.11M 1s
   300K .......... .......... .......... .......... .......... 45% 2.99M 0s
   350K .......... .......... .......... .......... .......... 51% 3.88M 0s
   400K .......... .......... .......... .......... .......... 58% 3.15M 0s
   450K .......... .......... .......... .......... .......... 64% 4.59M 0s
   500K .......... .......... .......... .......... .......... 71% 4.76M 0s
   550K .......... .......... .......... .......... .......... 77% 5.23M 0s
   600K .......... .......... .......... .......... .......... 84% 6.70M 0s
   650K .......... .......... .......... .......... .......... 90% 5.45M 0s
   700K .......... .......... .......... .......... .......... 97% 8.43M 0s
   750K .......... .......... .                               100% 6.36M=0.5s

2025-03-03 19:33:10 (1.67 MB/s) - ‘downloads_2024/Week_9th_2024.pdf’ saved [790156/790156]

--2025-03-03 19:33:10--  https://drive.google.com/uc?export=download&id=1lumtRYDosARGeEKcHfggt5epdtyitS1A
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_9th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1lumtRYDosARGeEKcHfggt5epdtyitS1A&export=download [following]
--2025-03-03 19:33:11--  https://drive.usercontent.google.com/download?id=1lumtRYDosARGeEKcHfggt5epdtyitS1A&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 691389 (675K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_10th_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  306K 2s
    50K .......... .......... .......... .......... .......... 14%  491K 2s
   100K .......... .......... .......... .......... .......... 22%  904K 1s
   150K .......... .......... .......... .......... .......... 29% 1.11M 1s
   200K .......... .......... .......... .......... .......... 37% 1.75M 1s
   250K .......... .......... .......... .......... .......... 44% 1.50M 1s
   300K .......... .......... .......... .......... .......... 51% 2.40M 0s
   350K .......... .......... .......... .......... .......... 59% 1.92M 0s
   400K .......... .......... .......... .......... .......... 66% 4.61M 0s
   450K .......... .......... .......... .......... .......... 74% 2.70M 0s
   500K .......... .......... .......... .......... .......... 81% 2.73M 0s
   550K .......... .......... .......... .......... .......... 88% 4.29M 0s
   600K .......... .......... .......... .......... .......... 96% 3.52M 0s
   650K .......... .......... .....                           100% 3.81M=0.5s

2025-03-03 19:33:16 (1.20 MB/s) - ‘downloads_2024/Week_10th_2024.pdf’ saved [691389/691389]

--2025-03-03 19:33:16--  https://drive.google.com/uc?export=download&id=1qYHV0dODb1_v3VgI49O-x5MAjMYYThBs
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_10th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1qYHV0dODb1_v3VgI49O-x5MAjMYYThBs&export=download [following]
--2025-03-03 19:33:17--  https://drive.usercontent.google.com/download?id=1qYHV0dODb1_v3VgI49O-x5MAjMYYThBs&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 978519 (956K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_11th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  284K 3s
    50K .......... .......... .......... .......... .......... 10%  466K 2s
   100K .......... .......... .......... .......... .......... 15%  905K 2s
   150K .......... .......... .......... .......... .......... 20%  958K 1s
   200K .......... .......... .......... .......... .......... 26% 1.95M 1s
   250K .......... .......... .......... .......... .......... 31% 1.20M 1s
   300K .......... .......... .......... .......... .......... 36% 1.82M 1s
   350K .......... .......... .......... .......... .......... 41% 2.11M 1s
   400K .......... .......... .......... .......... .......... 47% 2.72M 1s
   450K .......... .......... .......... .......... .......... 52% 1.54M 1s
   500K .......... .......... .......... .......... .......... 57% 5.77M 0s
   550K .......... .......... .......... .......... .......... 62% 2.09M 0s
   600K .......... .......... .......... .......... .......... 68% 2.73M 0s
   650K .......... .......... .......... .......... .......... 73% 3.97M 0s
   700K .......... .......... .......... .......... .......... 78% 5.54M 0s
   750K .......... .......... .......... .......... .......... 83% 7.25M 0s
   800K .......... .......... .......... .......... .......... 88% 2.63M 0s
   850K .......... .......... .......... .......... .......... 94% 7.25M 0s
   900K .......... .......... .......... .......... .......... 99% 4.96M 0s
   950K .....                                                 100% 99.2M=0.7s

2025-03-03 19:33:22 (1.40 MB/s) - ‘downloads_2024/Week_11th_2024.pdf’ saved [978519/978519]

--2025-03-03 19:33:22--  https://drive.google.com/uc?export=download&id=1gYke6h08qbm30tgTqi88YvneBSmh3cZW
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_11th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gYke6h08qbm30tgTqi88YvneBSmh3cZW&export=download [following]
--2025-03-03 19:33:23--  https://drive.usercontent.google.com/download?id=1gYke6h08qbm30tgTqi88YvneBSmh3cZW&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 788273 (770K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_12th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  364K 2s
    50K .......... .......... .......... .......... .......... 12%  556K 2s
   100K .......... .......... .......... .......... .......... 19% 1.20M 1s
   150K .......... .......... .......... .......... .......... 25% 1.49M 1s
   200K .......... .......... .......... .......... .......... 32% 2.02M 1s
   250K .......... .......... .......... .......... .......... 38% 2.29M 1s
   300K .......... .......... .......... .......... .......... 45% 3.11M 0s
   350K .......... .......... .......... .......... .......... 51% 3.15M 0s
   400K .......... .......... .......... .......... .......... 58% 3.15M 0s
   450K .......... .......... .......... .......... .......... 64% 4.76M 0s
   500K .......... .......... .......... .......... .......... 71% 4.66M 0s
   550K .......... .......... .......... .......... .......... 77% 5.87M 0s
   600K .......... .......... .......... .......... .......... 84% 4.40M 0s
   650K .......... .......... .......... .......... .......... 90% 4.96M 0s
   700K .......... .......... .......... .......... .......... 97% 8.58M 0s
   750K .......... .........                                  100% 9.61M=0.5s

2025-03-03 19:33:27 (1.67 MB/s) - ‘downloads_2024/Week_12th_2024.pdf’ saved [788273/788273]

--2025-03-03 19:33:27--  https://drive.google.com/uc?export=download&id=1FdbshEogmU7Ut4wY8iNKEVDE6J-4gGm_
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_12th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1FdbshEogmU7Ut4wY8iNKEVDE6J-4gGm_&export=download [following]
--2025-03-03 19:33:28--  https://drive.usercontent.google.com/download?id=1FdbshEogmU7Ut4wY8iNKEVDE6J-4gGm_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 782509 (764K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_13th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  323K 2s
    50K .......... .......... .......... .......... .......... 13%  588K 2s
   100K .......... .......... .......... .......... .......... 19% 1.04M 1s
   150K .......... .......... .......... .......... .......... 26% 1.31M 1s
   200K .......... .......... .......... .......... .......... 32% 1.91M 1s
   250K .......... .......... .......... .......... .......... 39% 2.55M 1s
   300K .......... .......... .......... .......... .......... 45% 3.05M 0s
   350K .......... .......... .......... .......... .......... 52% 2.69M 0s
   400K .......... .......... .......... .......... .......... 58% 3.20M 0s
   450K .......... .......... .......... .......... .......... 65% 3.41M 0s
   500K .......... .......... .......... .......... .......... 71% 5.22M 0s
   550K .......... .......... .......... .......... .......... 78% 4.50M 0s
   600K .......... .......... .......... .......... .......... 85% 4.98M 0s
   650K .......... .......... .......... .......... .......... 91% 3.40M 0s
   700K .......... .......... .......... .......... .......... 98% 5.68M 0s
   750K .......... ....                                       100% 23.2M=0.5s

2025-03-03 19:33:33 (1.54 MB/s) - ‘downloads_2024/Week_13th_2024.pdf’ saved [782509/782509]

--2025-03-03 19:33:33--  https://drive.google.com/uc?export=download&id=1VYR3JHc7T7bMnk8r7j83OfQHeJ4p_qJt
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_13th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1VYR3JHc7T7bMnk8r7j83OfQHeJ4p_qJt&export=download [following]
--2025-03-03 19:33:34--  https://drive.usercontent.google.com/download?id=1VYR3JHc7T7bMnk8r7j83OfQHeJ4p_qJt&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 755766 (738K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_14th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  321K 2s
    50K .......... .......... .......... .......... .......... 13%  486K 2s
   100K .......... .......... .......... .......... .......... 20% 1.29M 1s
   150K .......... .......... .......... .......... .......... 27%  576K 1s
   200K .......... .......... .......... .......... .......... 33% 16.8M 1s
   250K .......... .......... .......... .......... .......... 40%  591K 1s
   300K .......... .......... .......... .......... .......... 47% 17.4M 1s
   350K .......... .......... .......... .......... .......... 54% 5.59M 0s
   400K .......... .......... .......... .......... .......... 60% 3.32M 0s
   450K .......... .......... .......... .......... .......... 67% 4.61M 0s
   500K .......... .......... .......... .......... .......... 74% 1.86M 0s
   550K .......... .......... .......... .......... .......... 81% 2.37M 0s
   600K .......... .......... .......... .......... .......... 88% 3.86M 0s
   650K .......... .......... .......... .......... .......... 94% 3.65M 0s
   700K .......... .......... .......... ........             100% 5.41M=0.6s

2025-03-03 19:33:38 (1.23 MB/s) - ‘downloads_2024/Week_14th_2024.pdf’ saved [755766/755766]

--2025-03-03 19:33:39--  https://drive.google.com/uc?export=download&id=1p93pnw30hl6Dsg1Tz3UooGaX9ifs7bPS
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_14th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1p93pnw30hl6Dsg1Tz3UooGaX9ifs7bPS&export=download [following]
--2025-03-03 19:33:39--  https://drive.usercontent.google.com/download?id=1p93pnw30hl6Dsg1Tz3UooGaX9ifs7bPS&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 911568 (890K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_15th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  386K 2s
    50K .......... .......... .......... .......... .......... 11%  609K 2s
   100K .......... .......... .......... .......... .......... 16% 1.25M 1s
   150K .......... .......... .......... .......... .......... 22% 1.61M 1s
   200K .......... .......... .......... .......... .......... 28% 1.05M 1s
   250K .......... .......... .......... .......... .......... 33% 3.17M 1s
   300K .......... .......... .......... .......... .......... 39% 3.08M 1s
   350K .......... .......... .......... .......... .......... 44% 1.50M 0s
   400K .......... .......... .......... .......... .......... 50% 2.86M 0s
   450K .......... .......... .......... .......... .......... 56% 5.99M 0s
   500K .......... .......... .......... .......... .......... 61% 4.55M 0s
   550K .......... .......... .......... .......... .......... 67% 9.72M 0s
   600K .......... .......... .......... .......... .......... 73% 9.08M 0s
   650K .......... .......... .......... .......... .......... 78% 7.30M 0s
   700K .......... .......... .......... .......... .......... 84% 2.58M 0s
   750K .......... .......... .......... .......... .......... 89% 3.68M 0s
   800K .......... .......... .......... .......... .......... 95% 6.99M 0s
   850K .......... .......... .......... ..........           100% 4.90M=0.5s

2025-03-03 19:33:45 (1.77 MB/s) - ‘downloads_2024/Week_15th_2024.pdf’ saved [911568/911568]

--2025-03-03 19:33:45--  https://drive.google.com/uc?export=download&id=1Z4wqatbeSAiQogSZpSyfh0TPhtsIGbpO
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_15th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Z4wqatbeSAiQogSZpSyfh0TPhtsIGbpO&export=download [following]
--2025-03-03 19:33:46--  https://drive.usercontent.google.com/download?id=1Z4wqatbeSAiQogSZpSyfh0TPhtsIGbpO&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 797905 (779K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_16th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  316K 2s
    50K .......... .......... .......... .......... .......... 12%  536K 2s
   100K .......... .......... .......... .......... .......... 19%  784K 1s
   150K .......... .......... .......... .......... .......... 25% 1.96M 1s
   200K .......... .......... .......... .......... .......... 32% 1.11M 1s
   250K .......... .......... .......... .......... .......... 38% 2.07M 1s
   300K .......... .......... .......... .......... .......... 44% 2.19M 1s
   350K .......... .......... .......... .......... .......... 51% 1.58M 0s
   400K .......... .......... .......... .......... .......... 57% 1.48M 0s
   450K .......... .......... .......... .......... .......... 64% 1.94M 0s
   500K .......... .......... .......... .......... .......... 70% 2.94M 0s
   550K .......... .......... .......... .......... .......... 77% 3.49M 0s
   600K .......... .......... .......... .......... .......... 83% 4.19M 0s
   650K .......... .......... .......... .......... .......... 89% 2.94M 0s
   700K .......... .......... .......... .......... .......... 96% 2.36M 0s
   750K .......... .......... .........                       100% 2.90M=0.6s

2025-03-03 19:33:50 (1.25 MB/s) - ‘downloads_2024/Week_16th_2024.pdf’ saved [797905/797905]

✅ Downloaded: downloads_2024/Week_16th_2024.pdf

--2025-03-03 19:33:50--  https://drive.google.com/uc?export=download&id=181r-U1xoqvGFyer9pcRBisV_n23W5G90
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=181r-U1xoqvGFyer9pcRBisV_n23W5G90&export=download [following]
--2025-03-03 19:33:51--  https://drive.usercontent.google.com/download?id=181r-U1xoqvGFyer9pcRBisV_n23W5G90&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 920362 (899K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_17th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  429K 2s
    50K .......... .......... .......... .......... .......... 11%  867K 1s
   100K .......... .......... .......... .......... .......... 16% 1.62M 1s
   150K .......... .......... .......... .......... .......... 22% 1.74M 1s
   200K .......... .......... .......... .......... .......... 27% 2.20M 1s
   250K .......... .......... .......... .......... .......... 33% 4.09M 1s
   300K .......... .......... .......... .......... .......... 38% 3.41M 0s
   350K .......... .......... .......... .......... .......... 44% 4.37M 0s
   400K .......... .......... .......... .......... .......... 50% 4.48M 0s
   450K .......... .......... .......... .......... .......... 55% 3.55M 0s
   500K .......... .......... .......... .......... .......... 61% 5.86M 0s
   550K .......... .......... .......... .......... .......... 66% 5.10M 0s
   600K .......... .......... .......... .......... .......... 72% 7.64M 0s
   650K .......... .......... .......... .......... .......... 77% 7.15M 0s
   700K .......... .......... .......... .......... .......... 83% 8.30M 0s
   750K .......... .......... .......... .......... .......... 89% 7.91M 0s
   800K .......... .......... .......... .......... .......... 94% 7.03M 0s
   850K .......... .......... .......... .......... ........  100% 8.68M=0.4s

2025-03-03 19:33:56 (2.36 MB/s) - ‘downloads_2024/Week_17th_2024.pdf’ saved [920362/920362]

--2025-03-03 19:33:56--  https://drive.google.com/uc?export=download&id=1bnbn-nVYBADrMvxH67GkNaPq87YwzTYB

✅ Downloaded: downloads_2024/Week_17th_2024.pdf

Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1bnbn-nVYBADrMvxH67GkNaPq87YwzTYB&export=download [following]
--2025-03-03 19:33:56--  https://drive.usercontent.google.com/download?id=1bnbn-nVYBADrMvxH67GkNaPq87YwzTYB&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 866989 (847K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_18th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  370K 2s
    50K .......... .......... .......... .......... .......... 11%  587K 2s
   100K .......... .......... .......... .......... .......... 17% 1.15M 1s
   150K .......... .......... .......... .......... .......... 23% 1.10M 1s
   200K .......... .......... .......... .......... .......... 29% 1.65M 1s
   250K .......... .......... .......... .......... .......... 35% 2.39M 1s
   300K .......... .......... .......... .......... .......... 41% 1.70M 1s
   350K .......... .......... .......... .......... .......... 47% 3.77M 0s
   400K .......... .......... .......... .......... .......... 53% 2.60M 0s
   450K .......... .......... .......... .......... .......... 59% 3.36M 0s
   500K .......... .......... .......... .......... .......... 64% 4.10M 0s
   550K .......... .......... .......... .......... .......... 70% 4.71M 0s
   600K .......... .......... .......... .......... .......... 76% 2.99M 0s
   650K .......... .......... .......... .......... .......... 82% 9.89M 0s
   700K .......... .......... .......... .......... .......... 88% 3.76M 0s
   750K .......... .......... .......... .......... .......... 94% 4.76M 0s
   800K .......... .......... .......... .......... ......    100% 6.50M=0.5s

2025-03-03 19:34:02 (1.63 MB/s) - ‘downloads_2024/Week_18th_2024.pdf’ saved [866989/866989]

--2025-03-03 19:34:02--  https://drive.google.com/uc?export=download&id=1X0AHVK_AExD2cRKNk-7K5umZB_YdDMSR
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_18th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1X0AHVK_AExD2cRKNk-7K5umZB_YdDMSR&export=download [following]
--2025-03-03 19:34:02--  https://drive.usercontent.google.com/download?id=1X0AHVK_AExD2cRKNk-7K5umZB_YdDMSR&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2430 (2.4K) [text/html]
Saving to: ‘downloads_2024/Week_19th_2024.pdf’

     0K ..                                                    100% 7.70M=0s

2025-03-03 19:34:34 (7.70 MB/s) - ‘downloads_2024/Week_19th_2024.pdf’ saved [2430/2430]

--2025-03-03 19:34:34--  https://drive.google.com/uc?export=download&id=1BFi8uM9DDwb0Q-X-1vJ4pCiUJqMWryAe
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_19th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1BFi8uM9DDwb0Q-X-1vJ4pCiUJqMWryAe&export=download [following]
--2025-03-03 19:34:35--  https://drive.usercontent.google.com/download?id=1BFi8uM9DDwb0Q-X-1vJ4pCiUJqMWryAe&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 962411 (940K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_20th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  400K 2s
    50K .......... .......... .......... .......... .......... 10%  755K 2s
   100K .......... .......... .......... .......... .......... 15% 1.35M 1s
   150K .......... .......... .......... .......... .......... 21% 1.73M 1s
   200K .......... .......... .......... .......... .......... 26% 1.51M 1s
   250K .......... .......... .......... .......... .......... 31% 3.77M 1s
   300K .......... .......... .......... .......... .......... 37% 4.04M 1s
   350K .......... .......... .......... .......... .......... 42% 4.88M 0s
   400K .......... .......... .......... .......... .......... 47% 2.08M 0s
   450K .......... .......... .......... .......... .......... 53% 3.15M 0s
   500K .......... .......... .......... .......... .......... 58% 5.55M 0s
   550K .......... .......... .......... .......... .......... 63% 6.00M 0s
   600K .......... .......... .......... .......... .......... 69% 7.40M 0s
   650K .......... .......... .......... .......... .......... 74% 8.96M 0s
   700K .......... .......... .......... .......... .......... 79% 8.05M 0s
   750K .......... .......... .......... .......... .......... 85% 21.6M 0s
   800K .......... .......... .......... .......... .......... 90% 2.89M 0s
   850K .......... .......... .......... .......... .......... 95% 7.39M 0s
   900K .......... .......... .......... .........            100% 7.64M=0.4s

2025-03-03 19:34:40 (2.14 MB/s) - ‘downloads_2024/Week_20th_2024.pdf’ saved [962411/962411]

--2025-03-03 19:34:40--  https://drive.google.com/uc?export=download&id=1JtZCMGp5-wNBbBYv02xdCujs8r-ba6uh
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_20th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1JtZCMGp5-wNBbBYv02xdCujs8r-ba6uh&export=download [following]
--2025-03-03 19:34:41--  https://drive.usercontent.google.com/download?id=1JtZCMGp5-wNBbBYv02xdCujs8r-ba6uh&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 936534 (915K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_21st_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  334K 3s
    50K .......... .......... .......... .......... .......... 10%  730K 2s
   100K .......... .......... .......... .......... .......... 16% 1.21M 1s
   150K .......... .......... .......... .......... .......... 21% 1.45M 1s
   200K .......... .......... .......... .......... .......... 27% 1.93M 1s
   250K .......... .......... .......... .......... .......... 32%  706K 1s
   300K .......... .......... .......... .......... .......... 38%  676K 1s
   350K .......... .......... .......... .......... .......... 43%  722K 1s
   400K .......... .......... .......... .......... .......... 49%  721K 1s
   450K .......... .......... .......... .......... .......... 54% 4.33M 1s
   500K .......... .......... .......... .......... .......... 60% 4.13M 0s
   550K .......... .......... .......... .......... .......... 65% 4.18M 0s
   600K .......... .......... .......... .......... .......... 71% 1.12M 0s
   650K .......... .......... .......... .......... .......... 76% 3.50M 0s
   700K .......... .......... .......... .......... .......... 82% 5.88M 0s
   750K .......... .......... .......... .......... .......... 87% 4.23M 0s
   800K .......... .......... .......... .......... .......... 92% 6.87M 0s
   850K .......... .......... .......... .......... .......... 98% 5.33M 0s
   900K .......... ....                                       100% 5.01M=0.7s

2025-03-03 19:34:46 (1.22 MB/s) - ‘downloads_2024/Week_21st_2024.pdf’ saved [936534/936534]

--2025-03-03 19:34:46--  https://drive.google.com/uc?export=download&id=1J3BzC_ocEoWG2nbQiuRSvfbD7h1Vw0Bw
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_21st_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1J3BzC_ocEoWG2nbQiuRSvfbD7h1Vw0Bw&export=download [following]
--2025-03-03 19:34:47--  https://drive.usercontent.google.com/download?id=1J3BzC_ocEoWG2nbQiuRSvfbD7h1Vw0Bw&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 888674 (868K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_22nd_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  431K 2s
    50K .......... .......... .......... .......... .......... 11%  699K 1s
   100K .......... .......... .......... .......... .......... 17% 1.28M 1s
   150K .......... .......... .......... .......... .......... 23% 1.37M 1s
   200K .......... .......... .......... .......... .......... 28% 2.12M 1s
   250K .......... .......... .......... .......... .......... 34% 2.52M 1s
   300K .......... .......... .......... .......... .......... 40% 1.64M 0s
   350K .......... .......... .......... .......... .......... 46% 3.57M 0s
   400K .......... .......... .......... .......... .......... 51% 3.36M 0s
   450K .......... .......... .......... .......... .......... 57% 6.26M 0s
   500K .......... .......... .......... .......... .......... 63% 5.06M 0s
   550K .......... .......... .......... .......... .......... 69% 3.24M 0s
   600K .......... .......... .......... .......... .......... 74% 6.15M 0s
   650K .......... .......... .......... .......... .......... 80% 3.97M 0s
   700K .......... .......... .......... .......... .......... 86% 6.69M 0s
   750K .......... .......... .......... .......... .......... 92% 6.50M 0s
   800K .......... .......... .......... .......... .......... 97% 6.42M 0s
   850K .......... .......                                    100% 9.30M=0.4s

2025-03-03 19:34:52 (1.93 MB/s) - ‘downloads_2024/Week_22nd_2024.pdf’ saved [888674/888674]

--2025-03-03 19:34:52--  https://drive.google.com/uc?export=download&id=1oW5w73kaCCnaeJmQU6lJOwy-afvX_5O3
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_22nd_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1oW5w73kaCCnaeJmQU6lJOwy-afvX_5O3&export=download [following]
--2025-03-03 19:34:53--  https://drive.usercontent.google.com/download?id=1oW5w73kaCCnaeJmQU6lJOwy-afvX_5O3&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 804402 (786K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_23rd_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  338K 2s
    50K .......... .......... .......... .......... .......... 12%  605K 2s
   100K .......... .......... .......... .......... .......... 19% 1.06M 1s
   150K .......... .......... .......... .......... .......... 25% 1.37M 1s
   200K .......... .......... .......... .......... .......... 31% 2.47M 1s
   250K .......... .......... .......... .......... .......... 38% 2.52M 1s
   300K .......... .......... .......... .......... .......... 44% 2.10M 0s
   350K .......... .......... .......... .......... .......... 50% 3.79M 0s
   400K .......... .......... .......... .......... .......... 57% 4.95M 0s
   450K .......... .......... .......... .......... .......... 63% 3.65M 0s
   500K .......... .......... .......... .......... .......... 70% 4.75M 0s
   550K .......... .......... .......... .......... .......... 76% 5.73M 0s
   600K .......... .......... .......... .......... .......... 82% 7.27M 0s
   650K .......... .......... .......... .......... .......... 89% 7.12M 0s
   700K .......... .......... .......... .......... .......... 95% 5.92M 0s
   750K .......... .......... .......... .....                100% 9.81M=0.5s

2025-03-03 19:34:58 (1.69 MB/s) - ‘downloads_2024/Week_23rd_2024.pdf’ saved [804402/804402]

--2025-03-03 19:34:58--  https://drive.google.com/uc?export=download&id=1JquWgitb12IqEsQh34sX1IQ5g9L2IiW6
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_23rd_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1JquWgitb12IqEsQh34sX1IQ5g9L2IiW6&export=download [following]
--2025-03-03 19:34:59--  https://drive.usercontent.google.com/download?id=1JquWgitb12IqEsQh34sX1IQ5g9L2IiW6&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 903573 (882K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_24th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  309K 3s
    50K .......... .......... .......... .......... .......... 11%  220K 3s
   100K .......... .......... .......... .......... .......... 16% 6.18M 2s
   150K .......... .......... .......... .......... .......... 22%  955K 2s
   200K .......... .......... .......... .......... .......... 28% 1.50M 1s
   250K .......... .......... .......... .......... .......... 33% 1.48M 1s
   300K .......... .......... .......... .......... .......... 39% 1.39M 1s
   350K .......... .......... .......... .......... .......... 45% 2.31M 1s
   400K .......... .......... .......... .......... .......... 50% 3.08M 1s
   450K .......... .......... .......... .......... .......... 56% 5.23M 0s
   500K .......... .......... .......... .......... .......... 62% 2.03M 0s
   550K .......... .......... .......... .......... .......... 67% 4.99M 0s
   600K .......... .......... .......... .......... .......... 73% 4.88M 0s
   650K .......... .......... .......... .......... .......... 79% 3.37M 0s
   700K .......... .......... .......... .......... .......... 84% 7.00M 0s
   750K .......... .......... .......... .......... .......... 90% 3.97M 0s
   800K .......... .......... .......... .......... .......... 96% 1.95M 0s
   850K .......... .......... .......... ..                   100% 11.6M=0.7s

2025-03-03 19:35:04 (1.23 MB/s) - ‘downloads_2024/Week_24th_2024.pdf’ saved [903573/903573]

--2025-03-03 19:35:04--  https://drive.google.com/uc?export=download&id=1zNmXoGphKZJBRg5fv2ak9rOFS7isXJqv
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_24th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1zNmXoGphKZJBRg5fv2ak9rOFS7isXJqv&export=download [following]
--2025-03-03 19:35:04--  https://drive.usercontent.google.com/download?id=1zNmXoGphKZJBRg5fv2ak9rOFS7isXJqv&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 890037 (869K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_25th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  260K 3s
    50K .......... .......... .......... .......... .......... 11%  559K 2s
   100K .......... .......... .......... .......... .......... 17%  988K 2s
   150K .......... .......... .......... .......... .......... 23% 1.23M 1s
   200K .......... .......... .......... .......... .......... 28% 1.43M 1s
   250K .......... .......... .......... .......... .......... 34% 1.49M 1s
   300K .......... .......... .......... .......... .......... 40% 2.78M 1s
   350K .......... .......... .......... .......... .......... 46% 3.67M 1s
   400K .......... .......... .......... .......... .......... 51% 3.19M 0s
   450K .......... .......... .......... .......... .......... 57% 3.65M 0s
   500K .......... .......... .......... .......... .......... 63% 2.35M 0s
   550K .......... .......... .......... .......... .......... 69% 1.96M 0s
   600K .......... .......... .......... .......... .......... 74% 7.89M 0s
   650K .......... .......... .......... .......... .......... 80% 15.6M 0s
   700K .......... .......... .......... .......... .......... 86% 6.47M 0s
   750K .......... .......... .......... .......... .......... 92% 8.62M 0s
   800K .......... .......... .......... .......... .......... 97% 3.06M 0s
   850K .......... .........                                  100% 5.25M=0.6s

2025-03-03 19:35:09 (1.45 MB/s) - ‘downloads_2024/Week_25th_2024.pdf’ saved [890037/890037]

--2025-03-03 19:35:10--  https://drive.google.com/uc?export=download&id=1nqmrT1K0yMGVLubn_1c3OR5Tjh7OmIW1

✅ Downloaded: downloads_2024/Week_25th_2024.pdf

Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1nqmrT1K0yMGVLubn_1c3OR5Tjh7OmIW1&export=download [following]
--2025-03-03 19:35:10--  https://drive.usercontent.google.com/download?id=1nqmrT1K0yMGVLubn_1c3OR5Tjh7OmIW1&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1406461 (1.3M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_26th_2024.pdf’

     0K .......... .......... .......... .......... ..........  3%  389K 3s
    50K .......... .......... .......... .......... ..........  7%  453K 3s
   100K .......... .......... .......... .......... .......... 10% 3.04M 2s
   150K .......... .......... .......... .......... .......... 14%  489K 2s
   200K .......... .......... .......... .......... .......... 18% 3.99M 2s
   250K .......... .......... .......... .......... .......... 21% 3.67M 1s
   300K .......... .......... .......... .......... .......... 25%  547K 1s
   350K .......... .......... .......... .......... .......... 29% 4.34M 1s
   400K .......... .......... .......... .......... .......... 32% 9.70M 1s
   450K .......... .......... .......... .......... .......... 36% 9.07M 1s
   500K .......... .......... .......... .......... .......... 40% 1.42M 1s
   550K .......... .......... .......... .......... .......... 43%  340K 1s
   600K .......... .......... .......... .......... .......... 47% 7.65M 1s
   650K .......... .......... .......... .......... .......... 50% 18.6M 1s
   700K .......... .......... .......... .......... .......... 54% 23.4M 1s
   750K .......... .......... .......... .......... .......... 58% 58.3M 0s
   800K .......... .......... .......... .......... .......... 61% 51.0M 0s
   850K .......... .......... .......... .......... .......... 65%  100M 0s
   900K .......... .......... .......... .......... .......... 69% 81.5M 0s
   950K .......... .......... .......... .......... .......... 72% 56.1M 0s
  1000K .......... .......... .......... .......... .......... 76% 4.69M 0s
  1050K .......... .......... .......... .......... .......... 80% 3.30M 0s
  1100K .......... .......... .......... .......... .......... 83% 1.23M 0s
  1150K .......... .......... .......... .......... .......... 87% 2.45M 0s
  1200K .......... .......... .......... .......... .......... 91% 2.49M 0s
  1250K .......... .......... .......... .......... .......... 94% 2.42M 0s
  1300K .......... .......... .......... .......... .......... 98% 6.23M 0s
  1350K .......... .......... ...                             100% 2.22M=0.8s

2025-03-03 19:35:16 (1.61 MB/s) - ‘downloads_2024/Week_26th_2024.pdf’ saved [1406461/1406461]

✅ Downloaded: downloads_2024/Week_26th_2024.pdf

--2025-03-03 19:35:16--  https://drive.google.com/uc?export=download&id=1RuBZeJLDaedV8Vj7Y4RPdvv05rGbqiPD
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1RuBZeJLDaedV8Vj7Y4RPdvv05rGbqiPD&export=download [following]
--2025-03-03 19:35:17--  https://drive.usercontent.google.com/download?id=1RuBZeJLDaedV8Vj7Y4RPdvv05rGbqiPD&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1184244 (1.1M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_27th_2024.pdf’

     0K .......... .......... .......... .......... ..........  4%  287K 4s
    50K .......... .......... .......... .......... ..........  8%  449K 3s
   100K .......... .......... .......... .......... .......... 12%  875K 2s
   150K .......... .......... .......... .......... .......... 17% 1.25M 2s
   200K .......... .......... .......... .......... .......... 21% 1.24M 2s
   250K .......... .......... .......... .......... .......... 25% 1.52M 1s
   300K .......... .......... .......... .......... .......... 30% 1.85M 1s
   350K .......... .......... .......... .......... .......... 34% 2.56M 1s
   400K .......... .......... .......... .......... .......... 38% 3.13M 1s
   450K .......... .......... .......... .......... .......... 43%  461K 1s
   500K .......... .......... .......... .......... .......... 47% 74.2M 1s
   550K .......... .......... .......... .......... .......... 51% 50.3M 1s
   600K .......... .......... .......... .......... .......... 56% 58.4M 0s
   650K .......... .......... .......... .......... .......... 60% 79.0M 0s
   700K .......... .......... .......... .......... .......... 64% 53.1M 0s
   750K .......... .......... .......... .......... .......... 69% 86.3M 0s
   800K .......... .......... .......... .......... .......... 73% 74.9M 0s
   850K .......... .......... .......... .......... .......... 77% 1.20M 0s
   900K .......... .......... .......... .......... .......... 82% 8.86M 0s
   950K .......... .......... .......... .......... .......... 86% 12.5M 0s
  1000K .......... .......... .......... .......... .......... 90% 19.8M 0s
  1050K .......... .......... .......... .......... .......... 95% 12.3M 0s
  1100K .......... .......... .......... .......... .......... 99% 11.4M 0s
  1150K ......                                                100%  130K=0.7s

2025-03-03 19:35:24 (1.64 MB/s) - ‘downloads_2024/Week_27th_2024.pdf’ saved [1184244/1184244]

--2025-03-03 19:35:24--  https://drive.google.com/uc?export=download&id=1n4uySrCezHyJbLipKwwh1KfEewON_gDh
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_27th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1n4uySrCezHyJbLipKwwh1KfEewON_gDh&export=download [following]
--2025-03-03 19:35:25--  https://drive.usercontent.google.com/download?id=1n4uySrCezHyJbLipKwwh1KfEewON_gDh&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1708162 (1.6M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_28th_2024.pdf’

     0K .......... .......... .......... .......... ..........  2%  422K 4s
    50K .......... .......... .......... .......... ..........  5%  632K 3s
   100K .......... .......... .......... .......... ..........  8% 1.75M 2s
   150K .......... .......... .......... .......... .......... 11% 1.24M 2s
   200K .......... .......... .......... .......... .......... 14% 2.38M 2s
   250K .......... .......... .......... .......... .......... 17% 3.34M 1s
   300K .......... .......... .......... .......... .......... 20% 3.05M 1s
   350K .......... .......... .......... .......... .......... 23% 2.10M 1s
   400K .......... .......... .......... .......... .......... 26% 3.66M 1s
   450K .......... .......... .......... .......... .......... 29% 4.33M 1s
   500K .......... .......... .......... .......... .......... 32% 5.42M 1s
   550K .......... .......... .......... .......... .......... 35% 8.13M 1s
   600K .......... .......... .......... .......... .......... 38% 4.57M 1s
   650K .......... .......... .......... .......... .......... 41% 9.09M 1s
   700K .......... .......... .......... .......... .......... 44% 6.33M 0s
   750K .......... .......... .......... .......... .......... 47% 4.48M 0s
   800K .......... .......... .......... .......... .......... 50% 8.19M 0s
   850K .......... .......... .......... .......... .......... 53% 7.18M 0s
   900K .......... .......... .......... .......... .......... 56% 11.2M 0s
   950K .......... .......... .......... .......... .......... 59% 7.96M 0s
  1000K .......... .......... .......... .......... .......... 62% 10.2M 0s
  1050K .......... .......... .......... .......... .......... 65% 13.9M 0s
  1100K .......... .......... .......... .......... .......... 68% 13.0M 0s
  1150K .......... .......... .......... .......... .......... 71% 14.5M 0s
  1200K .......... .......... .......... .......... .......... 74% 14.0M 0s
  1250K .......... .......... .......... .......... .......... 77% 13.1M 0s
  1300K .......... .......... .......... .......... .......... 80% 20.8M 0s
  1350K .......... .......... .......... .......... .......... 83% 10.9M 0s
  1400K .......... .......... .......... .......... .......... 86% 18.6M 0s
  1450K .......... .......... .......... .......... .......... 89% 6.61M 0s
  1500K .......... .......... .......... .......... .......... 92% 10.6M 0s
  1550K .......... .......... .......... .......... .......... 95% 19.6M 0s
  1600K .......... .......... .......... .......... .......... 98% 7.64M 0s
  1650K .......... ........                                   100% 12.8M=0.5s

2025-03-03 19:35:30 (3.32 MB/s) - ‘downloads_2024/Week_28th_2024.pdf’ saved [1708162/1708162]

--2025-03-03 19:35:30--  https://drive.google.com/uc?export=download&id=1PtXxrZ4jXTUqN93sMi1mds74n-oxCrOm
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_28th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1PtXxrZ4jXTUqN93sMi1mds74n-oxCrOm&export=download [following]
--2025-03-03 19:35:31--  https://drive.usercontent.google.com/download?id=1PtXxrZ4jXTUqN93sMi1mds74n-oxCrOm&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1189800 (1.1M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_29th_2024.pdf’

     0K .......... .......... .......... .......... ..........  4%  252K 4s
    50K .......... .......... .......... .......... ..........  8%  501K 3s
   100K .......... .......... .......... .......... .......... 12%  588K 3s
   150K .......... .......... .......... .......... .......... 17% 1.27M 2s
   200K .......... .......... .......... .......... .......... 21% 1.26M 2s
   250K .......... .......... .......... .......... .......... 25% 1.16M 1s
   300K .......... .......... .......... .......... .......... 30% 1.75M 1s
   350K .......... .......... .......... .......... .......... 34% 3.17M 1s
   400K .......... .......... .......... .......... .......... 38% 1.32M 1s
   450K .......... .......... .......... .......... .......... 43% 1.88M 1s
   500K .......... .......... .......... .......... .......... 47% 2.18M 1s
   550K .......... .......... .......... .......... .......... 51% 4.11M 1s
   600K .......... .......... .......... .......... .......... 55% 4.88M 1s
   650K .......... .......... .......... .......... .......... 60% 4.85M 0s
   700K .......... .......... .......... .......... .......... 64% 2.45M 0s
   750K .......... .......... .......... .......... .......... 68% 2.62M 0s
   800K .......... .......... .......... .......... .......... 73% 2.08M 0s
   850K .......... .......... .......... .......... .......... 77% 4.48M 0s
   900K .......... .......... .......... .......... .......... 81% 5.08M 0s
   950K .......... .......... .......... .......... .......... 86% 3.25M 0s
  1000K .......... .......... .......... .......... .......... 90% 5.03M 0s
  1050K .......... .......... .......... .......... .......... 94% 3.24M 0s
  1100K .......... .......... .......... .......... .......... 98% 7.58M 0s
  1150K .......... .                                          100%  238K=0.8s

2025-03-03 19:35:37 (1.43 MB/s) - ‘downloads_2024/Week_29th_2024.pdf’ saved [1189800/1189800]

✅ Downloaded: downloads_2024/Week_29th_2024.pdf

--2025-03-03 19:35:37--  https://drive.google.com/uc?export=download&id=1iJ0y1mspBD68tD58TOCT75c-7YBzlo5L
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1iJ0y1mspBD68tD58TOCT75c-7YBzlo5L&export=download [following]
--2025-03-03 19:35:38--  https://drive.usercontent.google.com/download?id=1iJ0y1mspBD68tD58TOCT75c-7YBzlo5L&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1355383 (1.3M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_30th_2024.pdf’

     0K .......... .......... .......... .......... ..........  3%  276K 5s
    50K .......... .......... .......... .......... ..........  7%  519K 3s
   100K .......... .......... .......... .......... .......... 11%  831K 3s
   150K .......... .......... .......... .......... .......... 15% 1.17M 2s
   200K .......... .......... .......... .......... .......... 18% 1.09M 2s
   250K .......... .......... .......... .......... .......... 22% 2.23M 2s
   300K .......... .......... .......... .......... .......... 26% 1.97M 1s
   350K .......... .......... .......... .......... .......... 30% 2.76M 1s
   400K .......... .......... .......... .......... .......... 33% 1.47M 1s
   450K .......... .......... .......... .......... .......... 37% 2.39M 1s
   500K .......... .......... .......... .......... .......... 41% 3.45M 1s
   550K .......... .......... .......... .......... .......... 45% 4.38M 1s
   600K .......... .......... .......... .......... .......... 49% 3.93M 1s
   650K .......... .......... .......... .......... .......... 52% 6.19M 1s
   700K .......... .......... .......... .......... .......... 56% 6.17M 0s
   750K .......... .......... .......... .......... .......... 60% 3.47M 0s
   800K .......... .......... .......... .......... .......... 64% 2.97M 0s
   850K .......... .......... .......... .......... .......... 67% 5.42M 0s
   900K .......... .......... .......... .......... .......... 71% 6.60M 0s
   950K .......... .......... .......... .......... .......... 75% 7.65M 0s
  1000K .......... .......... .......... .......... .......... 79% 7.84M 0s
  1050K .......... .......... .......... .......... .......... 83% 4.40M 0s
  1100K .......... .......... .......... .......... .......... 86% 7.48M 0s
  1150K .......... .......... .......... .......... .......... 90% 11.4M 0s
  1200K .......... .......... .......... .......... .......... 94% 9.47M 0s
  1250K .......... .......... .......... .......... .......... 98% 10.1M 0s
  1300K .......... .......... ...                             100% 10.6M=0.7s

2025-03-03 19:35:43 (1.88 MB/s) - ‘downloads_2024/Week_30th_2024.pdf’ saved [1355383/1355383]

--2025-03-03 19:35:43--  https://drive.google.com/uc?export=download&id=1lKaVabDcJwf64Cj3C_v-IbLkA878JHxI
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_30th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1lKaVabDcJwf64Cj3C_v-IbLkA878JHxI&export=download [following]
--2025-03-03 19:35:43--  https://drive.usercontent.google.com/download?id=1lKaVabDcJwf64Cj3C_v-IbLkA878JHxI&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1220521 (1.2M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_31st_2024.pdf’

     0K .......... .......... .......... .......... ..........  4%  359K 3s
    50K .......... .......... .......... .......... ..........  8%  585K 2s
   100K .......... .......... .......... .......... .......... 12% 1.19M 2s
   150K .......... .......... .......... .......... .......... 16% 1.70M 1s
   200K .......... .......... .......... .......... .......... 20% 2.27M 1s
   250K .......... .......... .......... .......... .......... 25% 2.88M 1s
   300K .......... .......... .......... .......... .......... 29% 2.72M 1s
   350K .......... .......... .......... .......... .......... 33% 3.74M 1s
   400K .......... .......... .......... .......... .......... 37% 2.65M 1s
   450K .......... .......... .......... .......... .......... 41% 6.20M 1s
   500K .......... .......... .......... .......... .......... 46% 4.95M 0s
   550K .......... .......... .......... .......... .......... 50% 3.27M 0s
   600K .......... .......... .......... .......... .......... 54% 3.44M 0s
   650K .......... .......... .......... .......... .......... 58% 6.47M 0s
   700K .......... .......... .......... .......... .......... 62% 5.39M 0s
   750K .......... .......... .......... .......... .......... 67% 5.41M 0s
   800K .......... .......... .......... .......... .......... 71% 3.77M 0s
   850K .......... .......... .......... .......... .......... 75% 5.13M 0s
   900K .......... .......... .......... .......... .......... 79% 4.84M 0s
   950K .......... .......... .......... .......... .......... 83% 5.56M 0s
  1000K .......... .......... .......... .......... .......... 88% 8.42M 0s
  1050K .......... .......... .......... .......... .......... 92% 2.73M 0s
  1100K .......... .......... .......... .......... .......... 96% 9.08M 0s
  1150K .......... .......... .......... .......... .         100% 26.4M=0.5s

2025-03-03 19:35:49 (2.21 MB/s) - ‘downloads_2024/Week_31st_2024.pdf’ saved [1220521/1220521]

--2025-03-03 19:35:49--  https://drive.google.com/uc?export=download&id=1R48Z4mop81jCe8hRRq-yONUDo0y3ZRtt
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_31st_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1R48Z4mop81jCe8hRRq-yONUDo0y3ZRtt&export=download [following]
--2025-03-03 19:35:49--  https://drive.usercontent.google.com/download?id=1R48Z4mop81jCe8hRRq-yONUDo0y3ZRtt&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1320848 (1.3M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_32nd_2024.pdf’

     0K .......... .......... .......... .......... ..........  3%  322K 4s
    50K .......... .......... .......... .......... ..........  7%  671K 3s
   100K .......... .......... .......... .......... .......... 11% 1.06M 2s
   150K .......... .......... .......... .......... .......... 15% 1.25M 2s
   200K .......... .......... .......... .......... .......... 19% 1.81M 1s
   250K .......... .......... .......... .......... .......... 23% 2.38M 1s
   300K .......... .......... .......... .......... .......... 27% 1.54M 1s
   350K .......... .......... .......... .......... .......... 31% 2.62M 1s
   400K .......... .......... .......... .......... .......... 34% 3.07M 1s
   450K .......... .......... .......... .......... .......... 38% 6.63M 1s
   500K .......... .......... .......... .......... .......... 42% 2.30M 1s
   550K .......... .......... .......... .......... .......... 46% 3.44M 1s
   600K .......... .......... .......... .......... .......... 50% 4.23M 0s
   650K .......... .......... .......... .......... .......... 54% 3.08M 0s
   700K .......... .......... .......... .......... .......... 58% 4.09M 0s
   750K .......... .......... .......... .......... .......... 62% 9.08M 0s
   800K .......... .......... .......... .......... .......... 65% 5.30M 0s
   850K .......... .......... .......... .......... .......... 69% 6.36M 0s
   900K .......... .......... .......... .......... .......... 73% 5.10M 0s
   950K .......... .......... .......... .......... .......... 77% 2.50M 0s
  1000K .......... .......... .......... .......... .......... 81% 3.97M 0s
  1050K .......... .......... .......... .......... .......... 85% 8.15M 0s
  1100K .......... .......... .......... .......... .......... 89% 12.3M 0s
  1150K .......... .......... .......... .......... .......... 93% 23.8M 0s
  1200K .......... .......... .......... .......... .......... 96% 14.9M 0s
  1250K .......... .......... .......... .........            100% 18.6M=0.6s

2025-03-03 19:35:59 (2.13 MB/s) - ‘downloads_2024/Week_32nd_2024.pdf’ saved [1320848/1320848]

✅ Downloaded: downloads_2024/Week_32nd_2024.pdf

--2025-03-03 19:35:59--  https://drive.google.com/uc?export=download&id=1gZ3m-gJslKuzmCdhnit_Ha1au9-P8DTt
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gZ3m-gJslKuzmCdhnit_Ha1au9-P8DTt&export=download [following]
--2025-03-03 19:36:00--  https://drive.usercontent.google.com/download?id=1gZ3m-gJslKuzmCdhnit_Ha1au9-P8DTt&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1077366 (1.0M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_33rd_2024.pdf’

     0K .......... .......... .......... .......... ..........  4%  399K 3s
    50K .......... .......... .......... .......... ..........  9%  662K 2s
   100K .......... .......... .......... .......... .......... 14% 1.41M 1s
   150K .......... .......... .......... .......... .......... 19% 1.01M 1s
   200K .......... .......... .......... .......... .......... 23% 2.09M 1s
   250K .......... .......... .......... .......... .......... 28% 3.23M 1s
   300K .......... .......... .......... .......... .......... 33% 2.22M 1s
   350K .......... .......... .......... .......... .......... 38% 1.55M 1s
   400K .......... .......... .......... .......... .......... 42% 3.18M 1s
   450K .......... .......... .......... .......... .......... 47% 5.46M 0s
   500K .......... .......... .......... .......... .......... 52% 6.19M 0s
   550K .......... .......... .......... .......... .......... 57% 4.99M 0s
   600K .......... .......... .......... .......... .......... 61% 6.39M 0s
   650K .......... .......... .......... .......... .......... 66% 2.89M 0s
   700K .......... .......... .......... .......... .......... 71% 2.63M 0s
   750K .......... .......... .......... .......... .......... 76% 7.02M 0s
   800K .......... .......... .......... .......... .......... 80% 7.25M 0s
   850K .......... .......... .......... .......... .......... 85% 6.95M 0s
   900K .......... .......... .......... .......... .......... 90% 6.71M 0s
   950K .......... .......... .......... .......... .......... 95% 11.1M 0s
  1000K .......... .......... .......... .......... .......... 99% 14.9M 0s
  1050K ..                                                    100% 42.3K=0.5s

2025-03-03 19:36:04 (2.07 MB/s) - ‘downloads_2024/Week_33rd_2024.pdf’ saved [1077366/1077366]

--2025-03-03 19:36:04--  https://drive.google.com/uc?export=download&id=1sc7KamA4UXuB9YImoHPyO9yVAzEnChZ9
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_33rd_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1sc7KamA4UXuB9YImoHPyO9yVAzEnChZ9&export=download [following]
--2025-03-03 19:36:04--  https://drive.usercontent.google.com/download?id=1sc7KamA4UXuB9YImoHPyO9yVAzEnChZ9&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1181485 (1.1M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_34th_2024.pdf’

     0K .......... .......... .......... .......... ..........  4%  280K 4s
    50K .......... .......... .......... .......... ..........  8%  579K 3s
   100K .......... .......... .......... .......... .......... 13%  948K 2s
   150K .......... .......... .......... .......... .......... 17%  481K 2s
   200K .......... .......... .......... .......... .......... 21%  518K 2s
   250K .......... .......... .......... .......... .......... 26%  520K 2s
   300K .......... .......... .......... .......... .......... 30% 2.34M 1s
   350K .......... .......... .......... .......... .......... 34%  899K 1s
   400K .......... .......... .......... .......... .......... 39% 1.91M 1s
   450K .......... .......... .......... .......... .......... 43% 2.07M 1s
   500K .......... .......... .......... .......... .......... 47% 1.99M 1s
   550K .......... .......... .......... .......... .......... 52% 2.62M 1s
   600K .......... .......... .......... .......... .......... 56% 2.92M 1s
   650K .......... .......... .......... .......... .......... 60% 2.55M 1s
   700K .......... .......... .......... .......... .......... 65% 1.94M 0s
   750K .......... .......... .......... .......... .......... 69% 1.86M 0s
   800K .......... .......... .......... .......... .......... 73% 2.63M 0s
   850K .......... .......... .......... .......... .......... 78% 21.2M 0s
   900K .......... .......... .......... .......... .......... 82% 6.42M 0s
   950K .......... .......... .......... .......... .......... 86% 5.83M 0s
  1000K .......... .......... .......... .......... .......... 91% 6.64M 0s
  1050K .......... .......... .......... .......... .......... 95% 4.86M 0s
  1100K .......... .......... .......... .......... .......... 99% 8.35M 0s
  1150K ...                                                   100% 75.9K=0.9s

2025-03-03 19:36:10 (1.21 MB/s) - ‘downloads_2024/Week_34th_2024.pdf’ saved [1181485/1181485]

--2025-03-03 19:36:10--  https://drive.google.com/uc?export=download&id=1H1pLNH7m8t-Fi_bqPC1O7rjYY1BPgPSz
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_34th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1H1pLNH7m8t-Fi_bqPC1O7rjYY1BPgPSz&export=download [following]
--2025-03-03 19:36:11--  https://drive.usercontent.google.com/download?id=1H1pLNH7m8t-Fi_bqPC1O7rjYY1BPgPSz&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 786969 (769K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_35th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  207K 3s
    50K .......... .......... .......... .......... .......... 13%  343K 3s
   100K .......... .......... .......... .......... .......... 19%  217K 3s
   150K .......... .......... .......... .......... .......... 26%  457K 2s
   200K .......... .......... .......... .......... .......... 32%  505K 2s
   250K .......... .......... .......... .......... .......... 39% 1.03M 1s
   300K .......... .......... .......... .......... .......... 45% 1.17M 1s
   350K .......... .......... .......... .......... .......... 52% 2.67M 1s
   400K .......... .......... .......... .......... .......... 58% 1.34M 1s
   450K .......... .......... .......... .......... .......... 65% 1.07M 1s
   500K .......... .......... .......... .......... .......... 71% 1.87M 0s
   550K .......... .......... .......... .......... .......... 78% 4.38M 0s
   600K .......... .......... .......... .......... .......... 84% 3.08M 0s
   650K .......... .......... .......... .......... .......... 91% 3.54M 0s
   700K .......... .......... .......... .......... .......... 97% 4.41M 0s
   750K .......... ........                                   100% 3.65M=1.1s

2025-03-03 19:36:17 (699 KB/s) - ‘downloads_2024/Week_35th_2024.pdf’ saved [786969/786969]

--2025-03-03 19:36:17--  https://drive.google.com/uc?export=download&id=18fDoWSo9C7hGzSpYWdxI65CfNejBXhfH
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_35th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=18fDoWSo9C7hGzSpYWdxI65CfNejBXhfH&export=download [following]
--2025-03-03 19:36:18--  https://drive.usercontent.google.com/download?id=18fDoWSo9C7hGzSpYWdxI65CfNejBXhfH&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1129116 (1.1M) [application/octet-stream]
Saving to: ‘downloads_2024/Week_36th_2024.pdf’

     0K .......... .......... .......... .......... ..........  4%  277K 4s
    50K .......... .......... .......... .......... ..........  9%  515K 3s
   100K .......... .......... .......... .......... .......... 13%  788K 2s
   150K .......... .......... .......... .......... .......... 18%  951K 2s
   200K .......... .......... .......... .......... .......... 22% 1.31M 1s
   250K .......... .......... .......... .......... .......... 27% 1.54M 1s
   300K .......... .......... .......... .......... .......... 31% 1.78M 1s
   350K .......... .......... .......... .......... .......... 36% 2.44M 1s
   400K .......... .......... .......... .......... .......... 40% 2.89M 1s
   450K .......... .......... .......... .......... .......... 45% 2.29M 1s
   500K .......... .......... .......... .......... .......... 49% 2.00M 1s
   550K .......... .......... .......... .......... .......... 54% 2.73M 0s
   600K .......... .......... .......... .......... .......... 58% 2.99M 0s
   650K .......... .......... .......... .......... .......... 63% 6.25M 0s
   700K .......... .......... .......... .......... .......... 68% 5.20M 0s
   750K .......... .......... .......... .......... .......... 72% 5.43M 0s
   800K .......... .......... .......... .......... .......... 77% 3.34M 0s
   850K .......... .......... .......... .......... .......... 81% 5.88M 0s
   900K .......... .......... .......... .......... .......... 86% 6.59M 0s
   950K .......... .......... .......... .......... .......... 90% 4.37M 0s
  1000K .......... .......... .......... .......... .......... 95% 4.84M 0s
  1050K .......... .......... .......... .......... .......... 99% 4.12M 0s
  1100K ..                                                    100% 53.0K=0.7s

2025-03-03 19:36:24 (1.55 MB/s) - ‘downloads_2024/Week_36th_2024.pdf’ saved [1129116/1129116]

--2025-03-03 19:36:24--  https://drive.google.com/uc?export=download&id=1gZY4wd-G9b8Xk_3L18ZO1H17FsDGnTR7
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_36th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gZY4wd-G9b8Xk_3L18ZO1H17FsDGnTR7&export=download [following]
--2025-03-03 19:36:24--  https://drive.usercontent.google.com/download?id=1gZY4wd-G9b8Xk_3L18ZO1H17FsDGnTR7&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 740803 (723K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_37th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  269K 3s
    50K .......... .......... .......... .......... .......... 13%  485K 2s
   100K .......... .......... .......... .......... .......... 20%  997K 1s
   150K .......... .......... .......... .......... .......... 27%  966K 1s
   200K .......... .......... .......... .......... .......... 34% 1.94M 1s
   250K .......... .......... .......... .......... .......... 41% 1.69M 1s
   300K .......... .......... .......... .......... .......... 48% 2.25M 0s
   350K .......... .......... .......... .......... .......... 55% 2.44M 0s
   400K .......... .......... .......... .......... .......... 62% 2.37M 0s
   450K .......... .......... .......... .......... .......... 69% 3.91M 0s
   500K .......... .......... .......... .......... .......... 76% 3.63M 0s
   550K .......... .......... .......... .......... .......... 82% 2.90M 0s
   600K .......... .......... .......... .......... .......... 89% 5.95M 0s
   650K .......... .......... .......... .......... .......... 96% 3.03M 0s
   700K .......... .......... ...                             100% 15.3M=0.6s

2025-03-03 19:36:30 (1.23 MB/s) - ‘downloads_2024/Week_37th_2024.pdf’ saved [740803/740803]

--2025-03-03 19:36:30--  https://drive.google.com/uc?export=download&id=1E8QA8_G2Z6GnlDWwvE2VCa9JAf2kykDK
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_37th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E8QA8_G2Z6GnlDWwvE2VCa9JAf2kykDK&export=download [following]
--2025-03-03 19:36:32--  https://drive.usercontent.google.com/download?id=1E8QA8_G2Z6GnlDWwvE2VCa9JAf2kykDK&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 838695 (819K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_38th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  399K 2s
    50K .......... .......... .......... .......... .......... 12%  664K 1s
   100K .......... .......... .......... .......... .......... 18% 1.31M 1s
   150K .......... .......... .......... .......... .......... 24% 1.22M 1s
   200K .......... .......... .......... .......... .......... 30% 2.03M 1s
   250K .......... .......... .......... .......... .......... 36% 3.56M 1s
   300K .......... .......... .......... .......... .......... 42% 1.97M 0s
   350K .......... .......... .......... .......... .......... 48% 4.20M 0s
   400K .......... .......... .......... .......... .......... 54% 4.27M 0s
   450K .......... .......... .......... .......... .......... 61% 4.20M 0s
   500K .......... .......... .......... .......... .......... 67% 4.13M 0s
   550K .......... .......... .......... .......... .......... 73% 7.66M 0s
   600K .......... .......... .......... .......... .......... 79% 3.71M 0s
   650K .......... .......... .......... .......... .......... 85% 6.49M 0s
   700K .......... .......... .......... .......... .......... 91% 5.75M 0s
   750K .......... .......... .......... .......... .......... 97% 7.50M 0s
   800K .......... .........                                  100% 19.9M=0.4s

2025-03-03 19:36:36 (1.86 MB/s) - ‘downloads_2024/Week_38th_2024.pdf’ saved [838695/838695]

--2025-03-03 19:36:36--  https://drive.google.com/uc?export=download&id=1U9yLalb31zQCj8Sx6XVNqvSSl-j4rm_J
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_38th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1U9yLalb31zQCj8Sx6XVNqvSSl-j4rm_J&export=download [following]
--2025-03-03 19:36:37--  https://drive.usercontent.google.com/download?id=1U9yLalb31zQCj8Sx6XVNqvSSl-j4rm_J&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2433 (2.4K) [text/html]
Saving to: ‘downloads_2024/Week_39th_2024.pdf’

     0K ..                                                    100% 8.47M=0s

2025-03-03 19:36:38 (8.47 MB/s) - ‘downloads_2024/Week_39th_2024.pdf’ saved [2433/2433]

--2025-03-03 19:36:39--  https://drive.google.com/uc?export=download&id=1i-fun3UzME2SCF9TbM6EKJ3A12EBW0_L
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_39th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1i-fun3UzME2SCF9TbM6EKJ3A12EBW0_L&export=download [following]
--2025-03-03 19:36:39--  https://drive.usercontent.google.com/download?id=1i-fun3UzME2SCF9TbM6EKJ3A12EBW0_L&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 769703 (752K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_40th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  316K 2s
    50K .......... .......... .......... .......... .......... 13%  643K 2s
   100K .......... .......... .......... .......... .......... 19% 1.26M 1s
   150K .......... .......... .......... .......... .......... 26% 1.57M 1s
   200K .......... .......... .......... .......... .......... 33% 2.16M 1s
   250K .......... .......... .......... .......... .......... 39% 2.55M 1s
   300K .......... .......... .......... .......... .......... 46% 2.88M 0s
   350K .......... .......... .......... .......... .......... 53% 3.24M 0s
   400K .......... .......... .......... .......... .......... 59% 3.00M 0s
   450K .......... .......... .......... .......... .......... 66% 3.63M 0s
   500K .......... .......... .......... .......... .......... 73% 6.14M 0s
   550K .......... .......... .......... .......... .......... 79% 4.07M 0s
   600K .......... .......... .......... .......... .......... 86% 4.84M 0s
   650K .......... .......... .......... .......... .......... 93% 6.87M 0s
   700K .......... .......... .......... .......... .......... 99% 4.51M 0s
   750K .                                                     100% 36.9M=0.5s

2025-03-03 19:36:43 (1.60 MB/s) - ‘downloads_2024/Week_40th_2024.pdf’ saved [769703/769703]

--2025-03-03 19:36:43--  https://drive.google.com/uc?export=download&id=1Cpr_45rvsaUqWiA3pmumANhkOcHo5o1i
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_40th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Cpr_45rvsaUqWiA3pmumANhkOcHo5o1i&export=download [following]
--2025-03-03 19:36:44--  https://drive.usercontent.google.com/download?id=1Cpr_45rvsaUqWiA3pmumANhkOcHo5o1i&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 662220 (647K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_41st_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  386K 2s
    50K .......... .......... .......... .......... .......... 15%  622K 1s
   100K .......... .......... .......... .......... .......... 23% 1.22M 1s
   150K .......... .......... .......... .......... .......... 30% 1.06M 1s
   200K .......... .......... .......... .......... .......... 38% 2.37M 1s
   250K .......... .......... .......... .......... .......... 46% 1.96M 0s
   300K .......... .......... .......... .......... .......... 54% 1.50M 0s
   350K .......... .......... .......... .......... .......... 61% 3.01M 0s
   400K .......... .......... .......... .......... .......... 69% 4.16M 0s
   450K .......... .......... .......... .......... .......... 77% 3.82M 0s
   500K .......... .......... .......... .......... .......... 85% 3.89M 0s
   550K .......... .......... .......... .......... .......... 92% 3.28M 0s
   600K .......... .......... .......... .......... ......    100% 2.31M=0.5s

2025-03-03 19:36:49 (1.37 MB/s) - ‘downloads_2024/Week_41st_2024.pdf’ saved [662220/662220]

--2025-03-03 19:36:49--  https://drive.google.com/uc?export=download&id=1fdXlPXw4utZVWk5bevJ3B0lFKH7dmKNr
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_41st_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1fdXlPXw4utZVWk5bevJ3B0lFKH7dmKNr&export=download [following]
--2025-03-03 19:36:50--  https://drive.usercontent.google.com/download?id=1fdXlPXw4utZVWk5bevJ3B0lFKH7dmKNr&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 855072 (835K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_42nd_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  342K 2s
    50K .......... .......... .......... .......... .......... 11%  571K 2s
   100K .......... .......... .......... .......... .......... 17% 1.20M 1s
   150K .......... .......... .......... .......... .......... 23% 1.24M 1s
   200K .......... .......... .......... .......... .......... 29% 1.96M 1s
   250K .......... .......... .......... .......... .......... 35% 1.82M 1s
   300K .......... .......... .......... .......... .......... 41% 3.14M 1s
   350K .......... .......... .......... .......... .......... 47% 4.16M 0s
   400K .......... .......... .......... .......... .......... 53% 2.92M 0s
   450K .......... .......... .......... .......... .......... 59% 5.06M 0s
   500K .......... .......... .......... .......... .......... 65% 2.18M 0s
   550K .......... .......... .......... .......... .......... 71% 6.38M 0s
   600K .......... .......... .......... .......... .......... 77% 5.39M 0s
   650K .......... .......... .......... .......... .......... 83% 8.67M 0s
   700K .......... .......... .......... .......... .......... 89% 7.60M 0s
   750K .......... .......... .......... .......... .......... 95% 5.77M 0s
   800K .......... .......... .......... .....                100% 13.9M=0.5s

2025-03-03 19:36:55 (1.69 MB/s) - ‘downloads_2024/Week_42nd_2024.pdf’ saved [855072/855072]

--2025-03-03 19:36:55--  https://drive.google.com/uc?export=download&id=1ckrHLT9YO4ioQ7B0PQX1jlsSGkm_AsQT
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_42nd_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1ckrHLT9YO4ioQ7B0PQX1jlsSGkm_AsQT&export=download [following]
--2025-03-03 19:36:55--  https://drive.usercontent.google.com/download?id=1ckrHLT9YO4ioQ7B0PQX1jlsSGkm_AsQT&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 717757 (701K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_43rd_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  314K 2s
    50K .......... .......... .......... .......... .......... 14%  562K 1s
   100K .......... .......... .......... .......... .......... 21% 1.17M 1s
   150K .......... .......... .......... .......... .......... 28% 1.46M 1s
   200K .......... .......... .......... .......... .......... 35% 2.38M 1s
   250K .......... .......... .......... .......... .......... 42% 2.29M 0s
   300K .......... .......... .......... .......... .......... 49% 1.58M 0s
   350K .......... .......... .......... .......... .......... 57% 4.07M 0s
   400K .......... .......... .......... .......... .......... 64% 3.34M 0s
   450K .......... .......... .......... .......... .......... 71% 4.25M 0s
   500K .......... .......... .......... .......... .......... 78% 5.10M 0s
   550K .......... .......... .......... .......... .......... 85% 5.33M 0s
   600K .......... .......... .......... .......... .......... 92% 2.89M 0s
   650K .......... .......... .......... .......... .......... 99% 14.9M 0s
   700K                                                       100% 19.4M=0.5s

2025-03-03 19:37:00 (1.45 MB/s) - ‘downloads_2024/Week_43rd_2024.pdf’ saved [717757/717757]

--2025-03-03 19:37:00--  https://drive.google.com/uc?export=download&id=1IODkFK_BavqO6G38T5jFvlzkOpUjn3En
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_43rd_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1IODkFK_BavqO6G38T5jFvlzkOpUjn3En&export=download [following]
--2025-03-03 19:37:00--  https://drive.usercontent.google.com/download?id=1IODkFK_BavqO6G38T5jFvlzkOpUjn3En&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 829143 (810K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_44th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  157K 5s
    50K .......... .......... .......... .......... .......... 12%  352K 3s
   100K .......... .......... .......... .......... .......... 18%  744K 2s
   150K .......... .......... .......... .......... .......... 24% 62.0M 2s
   200K .......... .......... .......... .......... .......... 30% 1.01M 1s
   250K .......... .......... .......... .......... .......... 37%  236K 1s
   300K .......... .......... .......... .......... .......... 43%  453K 1s
   350K .......... .......... .......... .......... .......... 49% 2.86M 1s
   400K .......... .......... .......... .......... .......... 55% 26.8M 1s
   450K .......... .......... .......... .......... .......... 61%  487K 1s
   500K .......... .......... .......... .......... .......... 67%  457K 1s
   550K .......... .......... .......... .......... .......... 74%  951K 0s
   600K .......... .......... .......... .......... .......... 80%  871K 0s
   650K .......... .......... .......... .......... .......... 86%  843K 0s
   700K .......... .......... .......... .......... .......... 92%  939K 0s
   750K .......... .......... .......... .......... .......... 98%  899K 0s
   800K .........                                             100%  999K=1.4s

2025-03-03 19:37:06 (571 KB/s) - ‘downloads_2024/Week_44th_2024.pdf’ saved [829143/829143]

--2025-03-03 19:37:06--  https://drive.google.com/uc?export=download&id=1wsWUF7CyysoU1kObUGMj8AEkd_NdDfWb
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_44th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1wsWUF7CyysoU1kObUGMj8AEkd_NdDfWb&export=download [following]
--2025-03-03 19:37:07--  https://drive.usercontent.google.com/download?id=1wsWUF7CyysoU1kObUGMj8AEkd_NdDfWb&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 931968 (910K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_45th_2024.pdf’

     0K .......... .......... .......... .......... ..........  5%  309K 3s
    50K .......... .......... .......... .......... .......... 10%  510K 2s
   100K .......... .......... .......... .......... .......... 16%  899K 2s
   150K .......... .......... .......... .......... .......... 21% 1.33M 1s
   200K .......... .......... .......... .......... .......... 27% 1.88M 1s
   250K .......... .......... .......... .......... .......... 32% 2.57M 1s
   300K .......... .......... .......... .......... .......... 38% 1.61M 1s
   350K .......... .......... .......... .......... .......... 43% 2.37M 1s
   400K .......... .......... .......... .......... .......... 49% 3.71M 0s
   450K .......... .......... .......... .......... .......... 54% 4.49M 0s
   500K .......... .......... .......... .......... .......... 60% 4.11M 0s
   550K .......... .......... .......... .......... .......... 65% 3.48M 0s
   600K .......... .......... .......... .......... .......... 71% 4.37M 0s
   650K .......... .......... .......... .......... .......... 76% 3.60M 0s
   700K .......... .......... .......... .......... .......... 82% 3.57M 0s
   750K .......... .......... .......... .......... .......... 87% 3.81M 0s
   800K .......... .......... .......... .......... .......... 93% 8.14M 0s
   850K .......... .......... .......... .......... .......... 98% 5.35M 0s
   900K ..........                                            100%  114M=0.6s

2025-03-03 19:37:12 (1.58 MB/s) - ‘downloads_2024/Week_45th_2024.pdf’ saved [931968/931968]

--2025-03-03 19:37:12--  https://drive.google.com/uc?export=download&id=1aEF2AI-e-XLx29QWfA4JBAWsSmnu9QcZ
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_45th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1aEF2AI-e-XLx29QWfA4JBAWsSmnu9QcZ&export=download [following]
--2025-03-03 19:37:13--  https://drive.usercontent.google.com/download?id=1aEF2AI-e-XLx29QWfA4JBAWsSmnu9QcZ&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 823696 (804K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_46th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  303K 2s
    50K .......... .......... .......... .......... .......... 12%  535K 2s
   100K .......... .......... .......... .......... .......... 18%  909K 1s
   150K .......... .......... .......... .......... .......... 24% 1.55M 1s
   200K .......... .......... .......... .......... .......... 31% 1.95M 1s
   250K .......... .......... .......... .......... .......... 37% 2.09M 1s
   300K .......... .......... .......... .......... .......... 43% 2.16M 1s
   350K .......... .......... .......... .......... .......... 49% 3.86M 0s
   400K .......... .......... .......... .......... .......... 55% 3.81M 0s
   450K .......... .......... .......... .......... .......... 62% 4.22M 0s
   500K .......... .......... .......... .......... .......... 68% 6.05M 0s
   550K .......... .......... .......... .......... .......... 74% 3.24M 0s
   600K .......... .......... .......... .......... .......... 80% 2.94M 0s
   650K .......... .......... .......... .......... .......... 87% 5.40M 0s
   700K .......... .......... .......... .......... .......... 93% 7.13M 0s
   750K .......... .......... .......... .......... .......... 99% 7.71M 0s
   800K ....                                                  100% 2.62M=0.5s

2025-03-03 19:37:18 (1.52 MB/s) - ‘downloads_2024/Week_46th_2024.pdf’ saved [823696/823696]

--2025-03-03 19:37:18--  https://drive.google.com/uc?export=download&id=1gpGTcGuBf4ZyDJK6FXMsu9yxzw0WsiYi
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_46th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1gpGTcGuBf4ZyDJK6FXMsu9yxzw0WsiYi&export=download [following]
--2025-03-03 19:37:19--  https://drive.usercontent.google.com/download?id=1gpGTcGuBf4ZyDJK6FXMsu9yxzw0WsiYi&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 724069 (707K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_47th_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  299K 2s
    50K .......... .......... .......... .......... .......... 14%  608K 2s
   100K .......... .......... .......... .......... .......... 21%  623K 1s
   150K .......... .......... .......... .......... .......... 28%  518K 1s
   200K .......... .......... .......... .......... .......... 35% 44.8M 1s
   250K .......... .......... .......... .......... .......... 42% 3.29M 1s
   300K .......... .......... .......... .......... .......... 49% 3.06M 0s
   350K .......... .......... .......... .......... .......... 56% 3.51M 0s
   400K .......... .......... .......... .......... .......... 63% 3.37M 0s
   450K .......... .......... .......... .......... .......... 70% 1.58M 0s
   500K .......... .......... .......... .......... .......... 77% 2.07M 0s
   550K .......... .......... .......... .......... .......... 84% 3.17M 0s
   600K .......... .......... .......... .......... .......... 91% 6.50M 0s
   650K .......... .......... .......... .......... .......... 98% 5.17M 0s
   700K .......                                               100% 7.94M=0.6s

2025-03-03 19:37:23 (1.20 MB/s) - ‘downloads_2024/Week_47th_2024.pdf’ saved [724069/724069]

--2025-03-03 19:37:23--  https://drive.google.com/uc?export=download&id=1Wj4RIO8qr0ofT__7MdINowHUKXDe9x6l
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_47th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Wj4RIO8qr0ofT__7MdINowHUKXDe9x6l&export=download [following]
--2025-03-03 19:37:24--  https://drive.usercontent.google.com/download?id=1Wj4RIO8qr0ofT__7MdINowHUKXDe9x6l&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2427 (2.4K) [text/html]
Saving to: ‘downloads_2024/Week_48th_2024.pdf’

     0K ..                                                    100% 7.72M=0s

2025-03-03 19:37:25 (7.72 MB/s) - ‘downloads_2024/Week_48th_2024.pdf’ saved [2427/2427]

--2025-03-03 19:37:25--  https://drive.google.com/uc?export=download&id=1Ll2rwBUaPWq9q9BKPCRQGYnQ9Jwgk2dp
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_48th_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Ll2rwBUaPWq9q9BKPCRQGYnQ9Jwgk2dp&export=download [following]
--2025-03-03 19:37:26--  https://drive.usercontent.google.com/download?id=1Ll2rwBUaPWq9q9BKPCRQGYnQ9Jwgk2dp&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 617541 (603K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_49th_2024.pdf’

     0K .......... .......... .......... .......... ..........  8%  292K 2s
    50K .......... .......... .......... .......... .......... 16%  516K 1s
   100K .......... .......... .......... .......... .......... 24%  997K 1s
   150K .......... .......... .......... .......... .......... 33%  982K 1s
   200K .......... .......... .......... .......... .......... 41% 1.81M 1s
   250K .......... .......... .......... .......... .......... 49% 1.36M 0s
   300K .......... .......... .......... .......... .......... 58% 1.70M 0s
   350K .......... .......... .......... .......... .......... 66% 2.72M 0s
   400K .......... .......... .......... .......... .......... 74% 3.26M 0s
   450K .......... .......... .......... .......... .......... 82% 3.08M 0s
   500K .......... .......... .......... .......... .......... 91% 2.84M 0s
   550K .......... .......... .......... .......... .......... 99% 1.93M 0s
   600K ...                                                   100% 48.3M=0.6s

2025-03-03 19:37:30 (1.07 MB/s) - ‘downloads_2024/Week_49th_2024.pdf’ saved [617541/617541]

--2025-03-03 19:37:30--  https://drive.google.com/uc?export=download&id=1WL87VTQwhGyTmpCGGi3XanbcO4Ltj5cb
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_49th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1WL87VTQwhGyTmpCGGi3XanbcO4Ltj5cb&export=download [following]
--2025-03-03 19:37:31--  https://drive.usercontent.google.com/download?id=1WL87VTQwhGyTmpCGGi3XanbcO4Ltj5cb&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 804646 (786K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_50th_2024.pdf’

     0K .......... .......... .......... .......... ..........  6%  256K 3s
    50K .......... .......... .......... .......... .......... 12%  608K 2s
   100K .......... .......... .......... .......... .......... 19%  994K 1s
   150K .......... .......... .......... .......... .......... 25% 1.30M 1s
   200K .......... .......... .......... .......... .......... 31% 1.94M 1s
   250K .......... .......... .......... .......... .......... 38% 2.25M 1s
   300K .......... .......... .......... .......... .......... 44% 2.29M 1s
   350K .......... .......... .......... .......... .......... 50% 2.46M 0s
   400K .......... .......... .......... .......... .......... 57% 3.57M 0s
   450K .......... .......... .......... .......... .......... 63% 4.56M 0s
   500K .......... .......... .......... .......... .......... 69% 4.73M 0s
   550K .......... .......... .......... .......... .......... 76% 5.55M 0s
   600K .......... .......... .......... .......... .......... 82% 7.27M 0s
   650K .......... .......... .......... .......... .......... 89% 3.98M 0s
   700K .......... .......... .......... .......... .......... 95% 4.12M 0s
   750K .......... .......... .......... .....                100% 4.62M=0.5s

2025-03-03 19:37:36 (1.43 MB/s) - ‘downloads_2024/Week_50th_2024.pdf’ saved [804646/804646]

--2025-03-03 19:37:36--  https://drive.google.com/uc?export=download&id=1nLk5mRjguqOvbz__-6rFWBg7H0HvmRau
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443...

✅ Downloaded: downloads_2024/Week_50th_2024.pdf

connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1nLk5mRjguqOvbz__-6rFWBg7H0HvmRau&export=download [following]
--2025-03-03 19:37:37--  https://drive.usercontent.google.com/download?id=1nLk5mRjguqOvbz__-6rFWBg7H0HvmRau&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 654622 (639K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_51st_2024.pdf’

     0K .......... .......... .......... .......... ..........  7%  241K 2s
    50K .......... .......... .......... .......... .......... 15%  454K 2s
   100K .......... .......... .......... .......... .......... 23%  776K 1s
   150K .......... .......... .......... .......... .......... 31%  811K 1s
   200K .......... .......... .......... .......... .......... 39% 1.23M 1s
   250K .......... .......... .......... .......... .......... 46% 1.07M 1s
   300K .......... .......... .......... .......... .......... 54% 2.10M 0s
   350K .......... .......... .......... .......... .......... 62% 1.97M 0s
   400K .......... .......... .......... .......... .......... 70% 3.00M 0s
   450K .......... .......... .......... .......... .......... 78% 2.63M 0s
   500K .......... .......... .......... .......... .......... 86% 1.61M 0s
   550K .......... .......... .......... .......... .......... 93% 3.27M 0s
   600K .......... .......... .......... .........            100% 2.39M=0.7s

2025-03-03 19:37:42 (950 KB/s) - ‘downloads_2024/Week_51st_2024.pdf’ saved [654622/654622]

--2025-03-03 19:37:42--  https://drive.google.com/uc?export=download&id=1KSBt394Clc-njJck9l-MsxsO8wiZEP0_
Resolving drive.google.com (drive.google.com)... 142.250.199.142
Connecting to drive.google.com (drive.google.com)|142.250.199.142|:443... connected.

✅ Downloaded: downloads_2024/Week_51st_2024.pdf

HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1KSBt394Clc-njJck9l-MsxsO8wiZEP0_&export=download [following]
--2025-03-03 19:37:43--  https://drive.usercontent.google.com/download?id=1KSBt394Clc-njJck9l-MsxsO8wiZEP0_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.250.192.129
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.250.192.129|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 632353 (618K) [application/octet-stream]
Saving to: ‘downloads_2024/Week_52nd_2024.pdf’

     0K .......... .......... .......... .......... ..........  8%  217K 3s
    50K .......... .......... .......... .......... .......... 16%  403K 2s
   100K .......... .......... .......... .......... .......... 24%  792K 1s
   150K .......... .......... .......... .......... .......... 32% 1006K 1s
   200K .......... .......... .......... .......... .......... 40% 1.38M 1s
   250K .......... .......... .......... .......... .......... 48% 1.38M 1s
   300K .......... .......... .......... .......... .......... 56% 1.69M 0s
   350K .......... .......... .......... .......... .......... 64% 2.56M 0s
   400K .......... .......... .......... .......... .........

✅ Downloaded: downloads_2024/Week_52nd_2024.pdf
📁 All files are saved in: downloads_2024

. 72% 2.44M 0s
   450K .......... .......... .......... .......... .......... 80% 2.90M 0s
   500K .......... .......... .......... .......... .......... 89% 2.38M 0s
   550K .......... .......... .......... .......... .......... 97% 2.09M 0s
   600K .......... .......                                    100% 3.08M=0.7s

2025-03-03 19:37:47 (918 KB/s) - ‘downloads_2024/Week_52nd_2024.pdf’ saved [632353/632353]